source: .
url: 'https://redash.io'
collections:
  data_sources:
    output: true
    permalink: /data-sources/:path
  partners:
    output: true
    permalink: /integrations/:path
  integrations:
    output: true
    permalink: /data-sources/:path
  docs:
    output: true
    permalink: /docs/:path/
gems:
  - algoliasearch-jekyll
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-sitemap
algolia:
  application_id: 'QFZW4KBIT0'
  search_key: '1c74ec31459a537e57b2c94a01d061b7'
  index_name:     'docs'
  record_css_selector: 'p,ul,tr'
